# https://pre-commit.com/#creating-new-hooks
repos:
- repo: local
  hooks:
    - id: make-project
      name: make-project
      entry: make hook
      language: system

      stages: [commit]

      # needed because sytem hook
      pass_filenames: false
      always_run: true
